import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const SOURCE = join(ROOT, 'tokens', 'tokens.source.json');
const OUTPUT = join(ROOT, 'src', 'styles', 'tokens.css');

/**
 * Flatten a nested token object into { cssVarName: value }.
 * Stops descending at any object containing $value.
 * @param {Record<string, any>} obj
 * @param {string} [prefix]
 * @returns {Record<string, string>}
 */
export function flattenTokens(obj, prefix = '') {
  const out = {};
  for (const [key, val] of Object.entries(obj)) {
    const name = prefix ? `${prefix}-${key}` : key;
    if (val && typeof val === 'object' && '$value' in val) {
      out[name] = val.$value;
    } else if (val && typeof val === 'object') {
      Object.assign(out, flattenTokens(val, name));
    }
  }
  return out;
}

function renderBlock(selector, tokens) {
  let css = `${selector} {\n`;
  for (const [name, value] of Object.entries(tokens)) {
    css += `  --${name}: ${value};\n`;
  }
  css += '}\n\n';
  return css;
}

function main() {
  const raw = JSON.parse(readFileSync(SOURCE, 'utf8'));
  let css = '/* AUTO-GENERATED by tokens/sync.js — do not edit manually. */\n\n';

  css += renderBlock(':root', flattenTokens(raw.base ?? {}));
  css += renderBlock('[data-theme="dark"]', flattenTokens(raw.dark ?? {}));
  css += renderBlock('[data-theme="light"]', flattenTokens(raw.light ?? {}));

  mkdirSync(dirname(OUTPUT), { recursive: true });
  writeFileSync(OUTPUT, css);
  console.log(`✓ Tokens synced → ${OUTPUT}`);
}

// Only run main when invoked directly, not when imported by tests.
const isMain = import.meta.url === `file://${process.argv[1]}`;
if (isMain) main();
